-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 18:02:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `idAgendamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `horario` DATETIME NOT NULL,
  `cep` VARCHAR(15) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numeroEndereco` INT NOT NULL,
  PRIMARY KEY (`idAgendamento`),
  UNIQUE INDEX `idAgendamento_UNIQUE` (`idAgendamento` ASC) VISIBLE,
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidadão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidadão` (
  `idCidadao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(10) NULL,
  `logradouro` VARCHAR(15) NULL,
  `bairro` VARCHAR(25) NULL,
  `numeroEndereco` INT NULL,
  `email` VARCHAR(45) NULL,
  `Agendamento_idAgendamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCidadao`),
  UNIQUE INDEX `id_cidadao_UNIQUE` (`idCidadao` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `NOME_UNIQUE` (`nome` ASC) INVISIBLE,
  INDEX `nome_idx` (`nome` ASC) VISIBLE,
  INDEX `fk_Cidadão_Agendamento1_idx` (`Agendamento_idAgendamento` ASC) VISIBLE,
  CONSTRAINT `fk_Cidadão_Agendamento1`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VendaMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VendaMaterial` (
  `idVendaMaterial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `quantidadeVendida` DECIMAL(10,2) NOT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idVendaMaterial`),
  UNIQUE INDEX `idVendaMaterial_UNIQUE` (`idVendaMaterial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cooperado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooperado` (
  `idCooperado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `Agendamento_idAgendamento` INT UNSIGNED NOT NULL,
  `VendaMaterial_idVendaMaterial` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCooperado`),
  UNIQUE INDEX `idCooperado_UNIQUE` (`idCooperado` ASC) VISIBLE,
  INDEX `nome_idx` (`nome` ASC) VISIBLE,
  INDEX `fk_Cooperado_Agendamento1_idx` (`Agendamento_idAgendamento` ASC) VISIBLE,
  INDEX `fk_Cooperado_VendaMaterial1_idx` (`VendaMaterial_idVendaMaterial` ASC) VISIBLE,
  CONSTRAINT `fk_Cooperado_Agendamento1`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperado_VendaMaterial1`
    FOREIGN KEY (`VendaMaterial_idVendaMaterial`)
    REFERENCES `mydb`.`VendaMaterial` (`idVendaMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RotinaDeColeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RotinaDeColeta` (
  `idRotinaDeColeta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numeroEndereco` INT NOT NULL,
  `diaColeta` DATETIME NOT NULL,
  `horarioInicio` DATETIME NULL,
  `horarioTermino` DATETIME NULL,
  PRIMARY KEY (`idRotinaDeColeta`),
  UNIQUE INDEX `idRotinaDeColeta_UNIQUE` (`idRotinaDeColeta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticia` (
  `idNoticia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNoticia`),
  UNIQUE INDEX `idNoticia_UNIQUE` (`idNoticia` ASC) VISIBLE,
  INDEX `titulo_idx` (`titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orientacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orientacoes` (
  `idOrientacoes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrientacoes`),
  UNIQUE INDEX `idOrientacoes_UNIQUE` (`idOrientacoes` ASC) VISIBLE,
  INDEX `titulo_idx` (`titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cooperativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooperativa` (
  `idCooperativa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `inscricaoEstadual` VARCHAR(45) NOT NULL,
  `inscricaoMunicipal` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `numeroEndereco` INT NULL,
  `telefone` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `nomeRepresentante` VARCHAR(45) NOT NULL,
  `cpfRepresentante` VARCHAR(45) NOT NULL,
  `Cooperado_idCooperado` INT UNSIGNED NOT NULL,
  `VendaMaterial_idVendaMaterial` INT UNSIGNED NOT NULL,
  `Agendamento_idAgendamento` INT UNSIGNED NOT NULL,
  `RotinaDeColeta_idRotinaDeColeta` INT UNSIGNED NOT NULL,
  `Noticia_idNoticia` INT UNSIGNED NOT NULL,
  `Orientacoes_idOrientacoes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCooperativa`),
  UNIQUE INDEX `idCooperativa_UNIQUE` (`idCooperativa` ASC) VISIBLE,
  UNIQUE INDEX `inscricaoEstadual_UNIQUE` (`inscricaoEstadual` ASC) VISIBLE,
  UNIQUE INDEX `inscricaoMunicipal_UNIQUE` (`inscricaoMunicipal` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `nome_idx` (`nome` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Cooperado1_idx` (`Cooperado_idCooperado` ASC) VISIBLE,
  INDEX `fk_Cooperativa_VendaMaterial1_idx` (`VendaMaterial_idVendaMaterial` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Agendamento1_idx` (`Agendamento_idAgendamento` ASC) VISIBLE,
  INDEX `fk_Cooperativa_RotinaDeColeta1_idx` (`RotinaDeColeta_idRotinaDeColeta` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Noticia1_idx` (`Noticia_idNoticia` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Orientacoes1_idx` (`Orientacoes_idOrientacoes` ASC) VISIBLE,
  CONSTRAINT `fk_Cooperativa_Cooperado1`
    FOREIGN KEY (`Cooperado_idCooperado`)
    REFERENCES `mydb`.`Cooperado` (`idCooperado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperativa_VendaMaterial1`
    FOREIGN KEY (`VendaMaterial_idVendaMaterial`)
    REFERENCES `mydb`.`VendaMaterial` (`idVendaMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperativa_Agendamento1`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperativa_RotinaDeColeta1`
    FOREIGN KEY (`RotinaDeColeta_idRotinaDeColeta`)
    REFERENCES `mydb`.`RotinaDeColeta` (`idRotinaDeColeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperativa_Noticia1`
    FOREIGN KEY (`Noticia_idNoticia`)
    REFERENCES `mydb`.`Noticia` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cooperativa_Orientacoes1`
    FOREIGN KEY (`Orientacoes_idOrientacoes`)
    REFERENCES `mydb`.`Orientacoes` (`idOrientacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
