-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 16:10:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cidadao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidadao` (
  `idCidadao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cpf` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(10) NULL,
  `Logradouro` VARCHAR(15) NULL,
  `Bairro` VARCHAR(25) NULL,
  `numeroEndereco` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCidadao`),
  UNIQUE INDEX `CPF_UNIQUE` (`Cpf` ASC) VISIBLE,
  UNIQUE INDEX `NOME_UNIQUE` (`Nome` ASC) INVISIBLE,
  INDEX `nome_idx` (`Nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cooperado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooperado` (
  `idCooperado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(10) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCooperado`, `Cpf`),
  INDEX `nome_idx` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `idAgendamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NOT NULL,
  `Horario` DATETIME NOT NULL,
  `Cep` VARCHAR(15) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `numeroEndereco` INT NOT NULL,
  `Cidadao_idCidadao` INT UNSIGNED NOT NULL,
  `Cooperado_idCooperado` INT UNSIGNED NOT NULL,
  `Cooperado_Cpf` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `cep_UNIQUE` (`Cep` ASC) VISIBLE,
  INDEX `fk_Agendamento_Cidadao1_idx` (`Cidadao_idCidadao` ASC) VISIBLE,
  PRIMARY KEY (`idAgendamento`),
  INDEX `fk_Agendamento_Cooperado1_idx` (`Cooperado_idCooperado` ASC, `Cooperado_Cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_Cidadao1_idx`
    FOREIGN KEY (`Cidadao_idCidadao`)
    REFERENCES `mydb`.`Cidadao` (`idCidadao`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Agendamento_Cooperado1_idx`
    FOREIGN KEY (`Cooperado_idCooperado` , `Cooperado_Cpf`)
    REFERENCES `mydb`.`Cooperado` (`idCooperado` , `Cpf`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VendaMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VendaMaterial` (
  `idVendaMaterial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `quantidadeVendida` DECIMAL(10,2) NOT NULL,
  `Data` DATETIME NULL,
  `Cooperado_idCooperado` INT UNSIGNED NOT NULL,
  `Cooperado_Cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVendaMaterial`),
  INDEX `fk_VendaMaterial_Cooperado1_idx` (`Cooperado_idCooperado` ASC) VISIBLE,
  CONSTRAINT `fk_VendaMaterial_Cooperado1_idx`
    FOREIGN KEY (`Cooperado_idCooperado`)
    REFERENCES `mydb`.`Cooperado` (`idCooperado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RotinaDeColeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RotinaDeColeta` (
  `idRotinaDeColeta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cep` VARCHAR(45) NOT NULL,
  `Logradouro` VARCHAR(45) NOT NULL,
  `numeroEndereco` INT NOT NULL,
  `diaColeta` DATETIME NOT NULL,
  `horarioInicio` DATETIME NULL,
  `horarioTermino` DATETIME NULL,
  PRIMARY KEY (`idRotinaDeColeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticia` (
  `idNoticia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Conteudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNoticia`),
  INDEX `titulo_idx` (`Titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orientacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orientacoes` (
  `idOrientacoes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrientacoes`),
  INDEX `titulo_idx` (`Titulo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cooperativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooperativa` (
  `idCooperativa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `inscricaoEstadual` VARCHAR(45) NOT NULL,
  `inscricaoMunicipal` VARCHAR(45) NOT NULL,
  `Cnpj` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `numeroEndereco` INT NULL,
  `Telefone` VARCHAR(10) NULL,
  `Email` VARCHAR(45) NULL,
  `nomeRepresentante` VARCHAR(45) NOT NULL,
  `cpfRepresentante` VARCHAR(45) NOT NULL,
  `Cooperado_idCooperado` INT UNSIGNED NOT NULL,
  `VendaMaterial_idVendaMaterial` INT UNSIGNED NOT NULL,
  `Agendamento_idAgendamento` INT UNSIGNED NOT NULL,
  `RotinaDeColeta_idRotinaDeColeta` INT UNSIGNED NOT NULL,
  `Noticia_idNoticia` INT UNSIGNED NOT NULL,
  `Orientacoes_idOrientacoes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCooperativa`),
  UNIQUE INDEX `inscricaoEstadual_UNIQUE` (`inscricaoEstadual` ASC) VISIBLE,
  UNIQUE INDEX `inscricaoMunicipal_UNIQUE` (`inscricaoMunicipal` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`Cnpj` ASC) VISIBLE,
  INDEX `nome_idx` (`Nome` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Cooperado1_idx` (`Cooperado_idCooperado` ASC) VISIBLE,
  INDEX `fk_Cooperativa_VendaMaterial1_idx` (`VendaMaterial_idVendaMaterial` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Agendamento1_idx` (`Agendamento_idAgendamento` ASC) VISIBLE,
  INDEX `fk_Cooperativa_RotinaDeColeta1_idx` (`RotinaDeColeta_idRotinaDeColeta` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Noticia1_idx` (`Noticia_idNoticia` ASC) VISIBLE,
  INDEX `fk_Cooperativa_Orientacoes1_idx` (`Orientacoes_idOrientacoes` ASC) VISIBLE,
  CONSTRAINT `fk_Cooperativa_Cooperado1_idx`
    FOREIGN KEY (`Cooperado_idCooperado`)
    REFERENCES `mydb`.`Cooperado` (`idCooperado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cooperativa_VendaMaterial1_idx`
    FOREIGN KEY (`VendaMaterial_idVendaMaterial`)
    REFERENCES `mydb`.`VendaMaterial` (`idVendaMaterial`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cooperativa_Agendamento1_idx`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `mydb`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cooperativa_RotinaDeColeta1_idx`
    FOREIGN KEY (`RotinaDeColeta_idRotinaDeColeta`)
    REFERENCES `mydb`.`RotinaDeColeta` (`idRotinaDeColeta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cooperativa_Noticia1_idx`
    FOREIGN KEY (`Noticia_idNoticia`)
    REFERENCES `mydb`.`Noticia` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cooperativa_Orientacoes1_idx`
    FOREIGN KEY (`Orientacoes_idOrientacoes`)
    REFERENCES `mydb`.`Orientacoes` (`idOrientacoes`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
